name: localizely_sdk
description: Localizely SDK for Flutter enables Over-the-air translations update from Localizely cloud platform
version: 2.5.1
homepage: https://localizely.com/flutter-over-the-air/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^2.0.0
  build_config: ^1.0.0
  glob: ^2.0.0
  intl: ^0.18.0
  http: ^0.13.0
  logger: ^1.0.0
  path: ^1.8.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.0
  petitparser: ">=4.0.0 <6.0.0"
  shared_preferences: ^2.0.0
  uuid: ^3.0.0
  web_socket_channel: ^2.1.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^2.0.1
  mockito: ^5.0.12
  test: ^1.16.0

flutter:
  assets:
    - assets/images/localizely-logo.png
    - assets/images/2.0x/localizely-logo.png
    - assets/images/3.0x/localizely-logo.png
